name: Update Emacs Source

on:
  schedule:
    # At 4pm UTC (SG time midnight) past every 24th hour.
    - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  update-overlay:
    runs-on: macos-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Update inputs
        run: |
          ./emacs-source/update

      - name: Push commit with updated inputs
        run: |
          git pull --rebase --autostash
          git push
